# Generated by Django 5.2 on 2025-04-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallCenter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('ticket_id', models.IntegerField()),
                ('ticket_description', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='call_center_id_f96fb3_idx'), models.Index(fields=['user_id'], name='call_center_user_id_b61618_idx'), models.Index(fields=['ticket_id'], name='call_center_ticket__62423b_idx')],
            },
        ),
    ]
